### ISSUE TITLE
[CORE] - Init project

### ISSUE THREAD

**Issue by ArianeSpa** [ArianeSpa/RocketUI#1]
### DESCRIPTION 📝

Creating my first UI library to be published on npm and used in ofeel project !!! 😻 
Already tested a functional base with react typescript, styled-component, storybook (wepback and vite tested)

### TODO 🔨

- [x] Copy the functional base in this 
- [x] Add prettier config
- [x] Add eslint config
- [x] Add lint staged
- [x] Add husky
- [x] Start completing readme
- [x] Add keywords in package.jon
